#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Erik OS server edition: headless live image with the text installer.
set -eu

lb config noauto \
    --distribution trixie \
    --architecture amd64 \
    --binary-image iso-hybrid \
    --debian-installer live \
    --debian-installer-gui false \
    --system live \
    --archive-areas "main" \
    --checksums sha256 \
    --image-name erikos-server \
    --iso-application "Erik OS Server" \
    --iso-publisher "Genotomi" \
    --iso-volume ERIKOS_SERVER \
    "$@"
