#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Erik OS desktop edition: GNOME live image with the Calamares installer.
set -eu

lb config noauto \
    --distribution trixie \
    --architecture amd64 \
    --binary-image iso-hybrid \
    --debian-installer none \
    --system live \
    --archive-areas "main" \
    --checksums sha256 \
    --image-name erikos-desktop \
    --iso-application "Erik OS Desktop" \
    --iso-publisher "Genotomi" \
    --iso-volume ERIKOS_DESKTOP \
    "$@"
