#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Build Erik OS ISOs in WSL (or any Debian Trixie machine) as root.
#
#   sh scripts/build-iso.sh desktop|server|all       development build
#   sh scripts/build-iso.sh --release desktop|server|all
#
# Assembles editions/common + editions/<edition>, adds the Erik packages the
# edition lists, runs live-build, copies the ISO to releases/<VERSION>/ and
# audits it with scripts/audit-iso.py. An ISO that fails the audit is not
# releasable.
#
# Speed: the build tree lives in RAM (tmpfs) when there is room, because
# dpkg calls fsync for every file and that dominates a disk build. The
# package cache stays on disk between builds. Development builds compress
# the root file system with zstd (fast); release builds with xz (smallest).
# "all" builds both editions at the same time. GPUs cannot help: the work is
# package installation and CPU compression.
#
# Do not edit this file while it runs: sh reads it line by line.
set -eu

mode=dev
if [ "${1:-}" = --release ]; then mode=release; shift; fi
edition=${1:-}
case "$edition" in desktop|server|all) ;; *) echo "usage: $0 [--release] desktop|server|all" >&2; exit 2 ;; esac
[ "$(id -u)" -eq 0 ] || { echo "live-build needs root: run with sudo" >&2; exit 1; }

PROJECT_DIR=$(cd "$(dirname "$0")/.." && pwd)
WORK_DIR=${ERIK_WORK_DIR:-$HOME/erik-work}
DEB_OUT=$WORK_DIR/debs
VERSION=$(tr -d ' \r\n' < "$PROJECT_DIR/VERSION")
LOGS=$WORK_DIR/logs
mkdir -p "$LOGS"

python3 "$PROJECT_DIR/scripts/check-licenses.py"
python3 "$PROJECT_DIR/scripts/stage-artwork.py" --check
ls "$DEB_OUT"/erik-base_*.deb >/dev/null 2>&1 \
    || { echo "No Erik packages in $DEB_OUT: run scripts/build-packages.sh first" >&2; exit 1; }

if [ "$edition" = all ]; then
    start=$(date +%s)
    flag=; [ "$mode" = release ] && flag=--release
    sh "$0" $flag desktop > "$LOGS/all-desktop.out" 2>&1 & pid_d=$!
    sh "$0" $flag server > "$LOGS/all-server.out" 2>&1 & pid_s=$!
    rc=0
    wait $pid_d || rc=1
    wait $pid_s || rc=1
    tail -n 4 "$LOGS/all-desktop.out" "$LOGS/all-server.out"
    echo "both editions: $(( ($(date +%s) - start) / 60 )) min $(( ($(date +%s) - start) % 60 )) s"
    exit $rc
fi

BUILD=$WORK_DIR/iso/$edition
CACHE=$WORK_DIR/cache/$edition
mkdir -p "$BUILD" "$CACHE"

release_mounts() {
    mountpoint -q "$BUILD/cache" && umount "$BUILD/cache" || true
    mountpoint -q "$BUILD" && umount "$BUILD" || true
}

# Clean up the previous tree, then decide where to build.
if [ -d "$BUILD/config" ]; then
    (cd "$BUILD" && lb clean noauto >/dev/null 2>&1) || true
fi
release_mounts
[ -d "$BUILD/cache" ] && [ ! -L "$BUILD/cache" ] && cp -a "$BUILD/cache/." "$CACHE/" && rm -rf "$BUILD/cache"
rm -rf "$BUILD"; mkdir -p "$BUILD"

avail_gb=$(awk '/MemAvailable/ { print int($2 / 1048576) }' /proc/meminfo)
need_gb=14                      # desktop tree peaks around 10 GiB
if [ "$avail_gb" -ge "$need_gb" ] && [ "${ERIK_NO_TMPFS:-0}" != 1 ]; then
    mount -t tmpfs -o size=${need_gb}G,mode=0755 "erik-$edition" "$BUILD"
    where="RAM (tmpfs ${need_gb} GiB of ${avail_gb} GiB free)"
else
    where="disk"
fi
mkdir -p "$BUILD/cache"
mount --bind "$CACHE" "$BUILD/cache"
trap release_mounts EXIT

cp -r "$PROJECT_DIR/editions/common/." "$BUILD/"
cp -r "$PROJECT_DIR/editions/$edition/." "$BUILD/"
if grep -rlI "$(printf '\r')" "$BUILD/auto" "$BUILD/config" >/dev/null 2>&1; then
    echo "CRLF line endings in the edition tree; fix them before building" >&2
    exit 1
fi
chmod 0755 "$BUILD"/auto/* "$BUILD"/config/hooks/live/*.hook.chroot

# Development builds take Erik packages from the local build output.
# Release builds will take them from the signed Erik repository instead.
# live-build installs every .deb in packages.chroot, so copy only the Erik
# packages this edition lists, plus the Erik packages they depend on.
deb_of() { ls "$DEB_OUT/$1"_*_all.deb 2>/dev/null | head -n 1; }
want=$(cat "$BUILD"/config/package-lists/*.list.chroot | grep -o '^erik-[a-z0-9-]*' | sort -u | tr '\n' ' ')
todo=$want
while [ -n "$todo" ]; do
    next=
    for pkg in $todo; do
        deb=$(deb_of "$pkg")
        [ -n "$deb" ] || { echo "Erik package $pkg was not built" >&2; exit 1; }
        for dep in $(dpkg-deb -f "$deb" Depends | grep -o 'erik-[a-z0-9-]*'); do
            case " $want " in *" $dep "*) ;; *) want="$want $dep"; next="$next $dep" ;; esac
        done
    done
    todo=$next
done
mkdir -p "$BUILD/config/packages.chroot"
for pkg in $want; do
    cp "$(deb_of "$pkg")" "$BUILD/config/packages.chroot/"
done
echo "Erik packages in this image:" $want

if [ "$mode" = release ]; then
    compression="--chroot-squashfs-compression-type xz"
else
    compression="--chroot-squashfs-compression-type zstd --chroot-squashfs-compression-level 3"
fi

# Log every line with the elapsed time, so slow stages are visible.
log=$LOGS/$edition.log
status=$WORK_DIR/.lb-status-$edition
start=$(date +%s)
echo "Building $edition ($mode) in $where, log: $log"
cd "$BUILD"
{ { lb config $compression && lb build; } 2>&1; echo $? > "$status"; } | python3 -u -c '
import sys, time
t0 = time.time()
for line in sys.stdin:
    s = int(time.time() - t0)
    sys.stdout.write(f"[{s // 60:02d}:{s % 60:02d}] {line}")
' > "$log"
rc=$(cat "$status")
if [ "$rc" -ne 0 ]; then
    tail -n 20 "$log"
    echo "live-build failed ($rc), see $log" >&2
    exit 1
fi

iso=$(ls -t ./*.iso | head -n 1)
dest=$PROJECT_DIR/releases/$VERSION
mkdir -p "$dest"
name=erikos-$VERSION-$edition-amd64.iso
cp "$iso" "$dest/$name"
(cd "$dest" && sha256sum erikos-*.iso > SHA256SUMS)
cd /
release_mounts
trap - EXIT

elapsed=$(( $(date +%s) - start ))
echo "Stages:"
grep -E "^\[[0-9:]+\] P: (Begin|Build completed)" "$log" | sed 's/^/  /'
echo "Built in $(( elapsed / 60 )) min $(( elapsed % 60 )) s: $dest/$name"

if python3 "$PROJECT_DIR/scripts/audit-iso.py" "$dest/$name"; then
    echo "Audit PASS: $dest/$name.audit.txt"
else
    echo "Audit FAIL: this ISO must not be released. See $dest/$name.audit.txt" >&2
    exit 1
fi
